# Generated by Django 5.2.1 on 2025-05-25 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 6, 2, 57, 18389, tzinfo=datetime.timezone.utc)),
        ),
    ]
